### ISSUE TITLE
Header directive for any kind of published document - authors,title,collection,license

### ISSUE THREAD

**Issue by cnrdh** [npolar/npdc-common#27]
Datasets, publications, maps, and others should have the same title look
* Collection badge/name
* License image + open acces logo
* Title
* Author(s)
* Publication

**Comment by cnrdh** [comment]
![jgr-publication](https://cloud.githubusercontent.com/assets/35185/13043478/a8121b7e-d3c8-11e5-9e18-97e89fe8e305.png)

**Comment by baelter** [comment]
Implemented in dataset and publication
