### ISSUE TITLE
Build a list of components and write documentation

### ISSUE THREAD

**Issue by RDux** [npolar/npdc-common#34]
We have lots of components we can re-use but it's hard to see what is actually available and how we can use/configure them. We need to build an overview of components and document usage.

**Comment by cnrdh** [comment]
Shpuld we have a live demo on github pages instead of a bunch of screenshots?
Can we auto-build gh-pages from master using a hook? (You can setup gh-pages to serve anything in the /docs folder now)

**Comment by cnrdh** [comment]
Too unspecfic, closing
