### ISSUE TITLE
Exapandable search tooltip creates horizontal overflow

### ISSUE THREAD

**Issue by rexso** [npolar/npdc-common#8]
Newly added [tooltip](https://github.com/npolar/npdc-common/blob/65b61c652d7c47d8926eebd756a530ad2f096854/src/components/search/expandable-search/expandSearch.html#L11) creates horizontal overflow with visible scrollbar.

@baelter is probably most familiar with the corresponding [stylesheet](https://github.com/npolar/npdc-common/blob/65b61c652d7c47d8926eebd756a530ad2f096854/src/components/search/expandable-search/expandSearch.scss).

**Comment by rexso** [comment]
Also, related issue: tooltip positioning consistency. See attached image:

![tooltip-issues](https://cloud.githubusercontent.com/assets/5965109/10843645/747667ac-7efa-11e5-9b93-b44e054699b3.png)
*(pink line added as reference)*

**Comment by baelter** [comment]
Won't fix positioning issue, it's by design in angular material. Positiong in based on pointer positing. Just like normal title-attribs

**Comment by rexso** [comment]
@baelter No, it's relative to the position of the **<md-tooltip>** tag itself.
We just have to uniform the positioning of the tag in all components.. I'll look into it

**Comment by rexso** [comment]
Fixed for all current toolbar entries except the search component.
